### ISSUE TITLE
how this works ?

### ISSUE THREAD

**Issue by quasiperfect** [autokludge/ci-codeintel-helper#5]
i installed a fresh sublime 2
installed the package manager
installed the helper
called the helper and it created the file
now what ?

**Comment by amad** [comment]
It seems this is not issue but you posted it here ..
anyway you have to install CodeIntel package also to make this helper to work

Codeintel + ci-codeintel-helper

**Comment by quasiperfect** [comment]
thanks maybe this info should be added to the wiki
